/*
 * gm_room - static room definitions (generated by tools/asset_packer.py) and the
 * room runtime: current/pending room, room order, room start and switching.
 *
 * Tables are GMS2 room storage, reduced to what Spelunky Classic HD uses
 * (agents/HANDOFF_SLICE8.md section 2.1): instance layers, background layers and
 * asset layers holding legacy tiles (GMRGraphic). The runtime only borrows the
 * tables (no copies, no allocation).
 */
#ifndef GM_ROOM_H
#define GM_ROOM_H

#include "gm_instance.h"
#include "gm_object.h"

#include <stdbool.h>
#include <stdint.h>

#define GM_VIEW_COUNT 8

/* Upper bound on the registry size. Spelunky Classic HD has 33 rooms. */
#define GM_ROOM_MAX 128

#define GM_ROOM_NONE (-1)

/* ---- Static tables ------------------------------------------------------------ */

/* One of a room's 8 views (room .yy "views"; CreateViewFromStorage, yyView.js L200). */
typedef struct gm_room_view_def {
    bool visible;
    int xview, yview, wview, hview;
    int xport, yport, wport, hport;
    int hborder, vborder;
    int hspeed, vspeed;     /* -1 = unlimited */
    int object;             /* object (or instance) to follow, or -1 */
} gm_room_view_def_t;

/* YYLayerType values (Function_Layers.js L15). */
typedef enum gm_layer_kind {
    GM_LAYER_BACKGROUND = 1,
    GM_LAYER_INSTANCES = 2,
    GM_LAYER_ASSETS = 3
} gm_layer_kind_t;

typedef struct gm_room_layer_def {
    const char *name;
    int id;                 /* storage layer id (unique across the project) */
    int kind;               /* gm_layer_kind_t */
    int depth;
    bool visible;
    float x, y, hspeed, vspeed;
    /* GM_LAYER_BACKGROUND */
    int bg_sprite;          /* -1: colour only */
    bool bg_htiled, bg_vtiled, bg_stretch;
    uint32_t bg_colour;     /* .yy colour: alpha in the top byte, then B, G, R */
    /* GM_LAYER_ASSETS: the room's tiles[first_tile .. first_tile + tile_count) */
    int first_tile, tile_count;
} gm_room_layer_def_t;

/* A legacy tile (GMRGraphic): region (u, v, w, h) of frame 0 of `sprite`. */
typedef struct gm_room_tile_def {
    int sprite;
    int u, v, w, h;
    float x, y;
    float xscale, yscale;
    uint32_t colour;        /* alpha in the top byte, then B, G, R */
} gm_room_tile_def_t;

typedef struct gm_room_inst_def {
    int id;                 /* fixed id assigned by the packer (>= GM_INSTANCE_ID_BASE) */
    int object;
    float x, y;
    float xscale, yscale, angle;
    uint32_t colour;        /* alpha in the top byte, then B, G, R */
    float image_index, image_speed;
    int layer;              /* index into the room's layers */
    gm_event_fn code;       /* instance creation code, or NULL */
} gm_room_inst_def_t;

typedef struct gm_room_def {
    const char *name;
    int width, height;
    int speed;
    bool persistent;
    bool enable_views;
    gm_room_view_def_t views[GM_VIEW_COUNT];
    int layer_count;
    const gm_room_layer_def_t *layers;      /* .yy order */
    int tile_count;
    const gm_room_tile_def_t *tiles;
    int instance_count;
    const gm_room_inst_def_t *instances;    /* creation order */
    gm_event_fn code;                       /* room creation code, or NULL */
} gm_room_def_t;

/* ---- Runtime ---------------------------------------------------------------------
 *
 * Room start (_GameMaker.js StartRoom L1154-1517, GMS2 / g_isZeus branch):
 *   1. remove marked instances; Room End event (Other_5) for every active instance;
 *   2. take the persistent instances out of the active list (walking it from the end),
 *      then delete every other instance, active or deactivated, at once and without
 *      events (yyRoom.ClearInstances: no Destroy; CleanUp has no Spelunky handlers);
 *   3. switch the room globals (size, speed, views, layers), create *all* the new
 *      room's instances (fixed ids, depth of their layer; skipped when a live
 *      persistent instance has the id), then for each in creation order run
 *      PreCreate, Create and its instance creation code;
 *   4. append the persistent instances to the active list again;
 *   5. Game Start (first room only), room creation code with self == other == a
 *      dummy instance, Room Start.
 * Persistent rooms are not supported (Spelunky has none; the registry rejects them).
 *
 * Switching is deferred like New_Room: room_goto / room_restart / room_goto_next only
 * record a pending room; the game loop calls gm_room_switch_pending() at the end of
 * the tick (GameMaker_Tick L2408-2433).
 *
 * Events other than Create go through hooks.perform (the generated event table; the
 * runtime knows only gm_object_def_t's Create/Destroy/Step/... slots). */

#define GM_ROOM_FIRST_DYNAMIC_ID 1000000   /* g_room_maxid (LoadGame.js L746) */

/* Pending codes that are not rooms (New_Room, Globals.js L63-64). */
#define GM_ROOM_END_GAME (-100)       /* ROOM_ENDOFGAME: game_end() */
#define GM_ROOM_RESTART_GAME (-200)   /* ROOM_RESTARTGAME: game_restart() */

/* GML event codes (.yy eventType / eventNum, Globals.js GML_EVENT_*). */
#define GM_EVENT_TYPE_CREATE 0
#define GM_EVENT_TYPE_DESTROY 1
#define GM_EVENT_TYPE_ALARM 2
#define GM_EVENT_TYPE_STEP 3
#define GM_EVENT_TYPE_OTHER 7
#define GM_EVENT_TYPE_CLEAN_UP 12
#define GM_EVENT_TYPE_PRE_CREATE 14
#define GM_EVENT_OTHER_GAME_START 2
#define GM_EVENT_OTHER_GAME_END 3
#define GM_EVENT_OTHER_ROOM_START 4
#define GM_EVENT_OTHER_ROOM_END 5

typedef struct gm_room_hooks {
    /* Runs the (inherited) handler of event (type, number) on inst, with
     * self == other == inst. NULL: such events are skipped. */
    void (*perform)(gm_instance_t *inst, int type, int number);
    /* After the room globals, views and layers are set, before any instance of
     * the new room exists (e.g. to size the collision grid). May be NULL. */
    void (*room_begin)(int room);
} gm_room_hooks_t;

/* Installs the room table and room order (borrowed). Call after
 * gm_object_registry_init: instances must name valid objects and layers. On
 * failure the registry is empty and false is returned. */
bool gm_room_registry_init(const gm_room_def_t *rooms, int count, const int *order, int order_count);

/* Borrowed; NULL removes the hooks. */
void gm_room_set_hooks(const gm_room_hooks_t *hooks);

/* Forgets the current/pending room and counters (not the registry). */
void gm_room_reset(void);

int gm_room_count(void);
bool gm_room_exists(int room);
const gm_room_def_t *gm_room_get(int room);
const char *gm_room_get_name(int room);   /* "" for invalid rooms */

/* Room order (Function_Room.js L771-866). first/last: GM_ROOM_NONE if empty. */
int gm_room_first(void);
int gm_room_last(void);
int gm_room_next(int room);               /* GM_ROOM_NONE at the end */
int gm_room_previous(int room);

/* Current room, GM_ROOM_NONE before the game starts. */
int gm_room_current(void);

/* Pending switch: a room, GM_ROOM_END_GAME, GM_ROOM_RESTART_GAME or GM_ROOM_NONE. */
int gm_room_pending(void);

/* game_end / game_restart (Function_Room.js L875-910): only set the pending code;
 * the game loop acts on it at the end of the tick. */
void gm_room_game_end(void);
void gm_room_game_restart(void);

/* The restart itself (GameMaker_Tick L2418-2423): Run_EndGame removes every
 * instance, persistent ones included, without events; ResetAll drops all cameras;
 * StartGame starts the first room with Game Start. Globals and the heap stay. */
bool gm_room_restart_game(void);

/* Event gate of yyObject.PerformEvent (yyObject.js L702-715): while a switch is
 * pending (New_Room != -1) every event of type `type` (GML numbering) on inst is
 * skipped, except Clean Up, and except Create, PreCreate, Destroy, Alarm and Other
 * when inst (or the current room) is persistent. Every event dispatch must ask. */
bool gm_room_event_blocked(const gm_instance_t *inst, int type);

/* room_goto: an invalid room is an error (counted, gm_room_errors) and a no-op. */
bool gm_room_goto(int room);
void gm_room_restart(void);
void gm_room_goto_next(void);             /* no-op at the end of the room order */
void gm_room_goto_previous(void);

/* Starts the game in the first room of the room order (with Game Start). Dynamic
 * instance ids start at GM_ROOM_FIRST_DYNAMIC_ID from here on. */
bool gm_room_start_game(void);

/* Performs the pending switch if it names a room (not the end/restart codes).
 * Returns true if a room was started. */
bool gm_room_switch_pending(void);

/* Runs StartRoom directly (tests, the game boot). */
bool gm_room_start(int room, bool starting);

/* Room built-ins of the current room (room_width ... are settable in GML). */
float gm_room_width(void);
float gm_room_height(void);
float gm_room_speed(void);
bool gm_room_persistent(void);
const char *gm_room_caption(void);
void gm_room_set_width(float w);
void gm_room_set_height(float h);
void gm_room_set_speed(float s);
void gm_room_set_persistent(bool p);
void gm_room_set_caption(const char *caption);   /* copied (truncated) */

/* Event pass over the active list, from the end, skipping marked instances and
 * those created during the pass (yyInstanceManager.PerformEvent, yyInstance.js
 * L3718). Uses hooks.perform. */
void gm_room_perform_event_all(int type, int number);

/* Diagnostics: invalid room_goto calls; room instances not created (pool full). */
long gm_room_errors(void);
long gm_room_overflows(void);

#endif /* GM_ROOM_H */
