/*
 * gml_rt - support layer for code generated by tools/gml2c (slice 7).
 *
 * Generated scripts and events include this header (through gml_game.h). It
 * implements GML expression semantics on top of the runtime, following the
 * GameMaker-HTML5 runner, which is the parity oracle:
 *
 *  - reals compare with an epsilon of 1e-5 (yyfequal / yyfless ...,
 *    Function_Maths.js L2073-2152); NaN comparisons are false;
 *  - truthiness is `value > 0.5` (yyGetBool, yyTypes.js L318);
 *  - `obj.var` reads/writes the instance yyInst() resolves to: self for
 *    self/all, other, an instance id, or the first instance of an object
 *    (yyInstance.js L3762). Unresolvable targets read 0 and ignore writes
 *    (the runner raises an error);
 *  - `a div b`, `a mod b`, bitwise and shift operators follow yyfdiv,
 *    yyfmod (JS %), yyfbitand/or/xor (ToInt32) and yyfbitshiftleft/right.
 *
 * Calling convention of generated code: every script and event receives the
 * current `self` and `other` instances, both non-NULL (the game loop passes
 * self as other outside collision events). Inside `with` the emitter rebinds
 * them while gm_with (gm_with.h) iterates the snapshot and tracks the
 * context; a function that leaves a with body early (return / exit) first
 * calls gm_with_unwind. Event wrappers push the (self, other) context through
 * gml_event_push. Scripts are fixed-arity C functions (one typed parameter per
 * argument; missing arguments get 0 / "" / undefined); scripts that use
 * argument[i] or argument_count also receive `int argc`, the number of
 * arguments actually passed. Only script_execute with a computed index goes
 * through the boxed (argc, argv) trampolines.
 *
 * Value representations (tools/gml2c/c_emitter.py): `float` for reals,
 * `const char *` for statically typed strings, gm_value_t for arrays and
 * values of unknown type. String pointers are string literals or gm_heap
 * strings (the collector relocates them, see gm_heap.h); every helper that
 * takes one treats NULL as "".
 *
 * Memory: strings and arrays live in gm_heap. gml_collect_garbage() must only
 * be called at a safe point (no generated code on the stack).
 */
#ifndef GML_RT_H
#define GML_RT_H

#include "gm_audio.h"
#include "gm_collision.h"
#include "gm_draw.h"
#include "gm_ds.h"
#include "gm_file.h"
#include "gm_heap.h"
#include "gm_input.h"
#include "gm_instance.h"
#include "gm_layer.h"
#include "gm_loop.h"
#include "gm_math.h"
#include "gm_object.h"
#include "gm_room.h"
#include "gm_sprite.h"
#include "gm_view.h"
#include "gm_value.h"
#include "gm_with.h"

#include "gml_api.h"

#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>



/* ---- values --------------------------------------------------------------------- */

static inline gm_value_t gml_vreal(float d)
{
    return gm_value_real(d);
}

static inline gm_value_t gml_vundef(void)
{
    return gm_value_undefined();
}

/* Boxes a static string (literal or gm_heap string: ownership is by address,
 * so the box stays collectable). */
static inline gm_value_t gml_vs(const char *s)
{
    return gm_value_string(s);
}

/* yyGetReal */
static inline float gml_real(gm_value_t v)
{
    return v.kind == GM_VALUE_REAL ? v.real : gm_value_to_real(v);
}

/* yyGetBool on a real. */
static inline int gml_truthy(float d)
{
    return d > 0.5f;
}

static inline int gml_vtruthy(gm_value_t v)
{
    return gm_value_to_bool(v);
}

/* ---- comparisons (yyfequal, yyfless, ...) -------------------------------------------- */

static inline int gml_eq(float a, float b)
{
    return gm_compare_real(a, b) == 0;
}

static inline int gml_ne(float a, float b)
{
    return gm_compare_real(a, b) != 0;
}

static inline int gml_lt(float a, float b)
{
    int r = gm_compare_real(a, b);
    return r != GM_CMP_UNORDERED && r < 0;
}

static inline int gml_le(float a, float b)
{
    int r = gm_compare_real(a, b);
    return r != GM_CMP_UNORDERED && r <= 0;
}

static inline int gml_gt(float a, float b)
{
    int r = gm_compare_real(a, b);
    return r != GM_CMP_UNORDERED && r > 0;
}

static inline int gml_ge(float a, float b)
{
    int r = gm_compare_real(a, b);
    return r != GM_CMP_UNORDERED && r >= 0;
}

static inline int gml_veq(gm_value_t a, gm_value_t b)
{
    return gm_value_compare(a, b) == 0;
}

static inline int gml_vne(gm_value_t a, gm_value_t b)
{
    return gm_value_compare(a, b) != 0;
}

static inline int gml_vlt(gm_value_t a, gm_value_t b)
{
    int r = gm_value_compare(a, b);
    return r != GM_CMP_UNORDERED && r < 0;
}

static inline int gml_vle(gm_value_t a, gm_value_t b)
{
    int r = gm_value_compare(a, b);
    return r != GM_CMP_UNORDERED && r <= 0;
}

static inline int gml_vgt(gm_value_t a, gm_value_t b)
{
    int r = gm_value_compare(a, b);
    return r != GM_CMP_UNORDERED && r > 0;
}

static inline int gml_vge(gm_value_t a, gm_value_t b)
{
    int r = gm_value_compare(a, b);
    return r != GM_CMP_UNORDERED && r >= 0;
}

/* switch/case match: same kind, reals within epsilon, strings equal. */
int gml_case(gm_value_t subject, gm_value_t label);

static inline int gml_rcase(float subject, float label)
{
    return gm_compare_real(subject, label) == 0;
}

/* ---- static strings --------------------------------------------------------------------- */

static inline const char *gml_s(const char *s)
{
    return s != NULL ? s : "";
}

/* yyCompareVal on two strings: code-unit order (bytes of UTF-8 text). */
int gml_str_cmp(const char *a, const char *b);

static inline int gml_str_eq(const char *a, const char *b)
{
    return gml_str_cmp(a, b) == 0;
}

static inline int gml_str_ne(const char *a, const char *b)
{
    return gml_str_cmp(a, b) != 0;
}

static inline int gml_str_lt(const char *a, const char *b)
{
    return gml_str_cmp(a, b) < 0;
}

static inline int gml_str_le(const char *a, const char *b)
{
    return gml_str_cmp(a, b) <= 0;
}

static inline int gml_str_gt(const char *a, const char *b)
{
    return gml_str_cmp(a, b) > 0;
}

static inline int gml_str_ge(const char *a, const char *b)
{
    return gml_str_cmp(a, b) >= 0;
}

static inline int gml_str_case(const char *subject, const char *label)
{
    return gml_str_cmp(subject, label) == 0;
}

/* string + string (in gm_heap). */
static inline const char *gml_concat(const char *a, const char *b)
{
    return gm_heap_str_concat(a, b);
}

/* Conversions of static strings: yyGetReal, yyGetBool, real(). */
float gml_str_real(const char *s);
int gml_str_truthy(const char *s);
float gml_str_to_real(const char *s);

/* string(x) for a real (in gm_heap, or a literal). */
const char *gml_real_str(float d);

/* A value as a static string: strings as is, anything else through
 * string() ("undefined" for undefined). */
const char *gml_as_str(gm_value_t v);

/* ---- arithmetic ------------------------------------------------------------------------ */

/* yyfplus on values: string + string concatenates (in gm_heap), anything
 * else adds as reals. */
gm_value_t gml_add(gm_value_t a, gm_value_t b);

float gml_div(float a, float b); /* yyfdiv */

static inline float gml_mod(float a, float b)
{
    return fmodf(a, b); /* JS % */
}

static inline float gml_bitand(float a, float b)
{
    return (float)(gm_to_int32(a) & gm_to_int32(b));
}

static inline float gml_bitor(float a, float b)
{
    return (float)(gm_to_int32(a) | gm_to_int32(b));
}

static inline float gml_bitxor(float a, float b)
{
    return (float)(gm_to_int32(a) ^ gm_to_int32(b));
}

static inline float gml_bitnot(float a)
{
    return (float)(~gm_to_int32(a));
}

float gml_shl(float a, float n);
float gml_shr(float a, float n);

/* ---- instances --------------------------------------------------------------------------- */

/* Instance as a GML value (its id), noone for NULL. */
static inline float gml_id(const gm_instance_t *p)
{
    return p != NULL ? (float)p->id : (float)GM_NOONE;
}

/* Object/instance argument as passed to runtime queries. */
static inline int gml_target(float t)
{
    return (int)gm_to_int32(t);
}

/* yyInst(): the single instance `obj.var` refers to (see file comment). */
gm_instance_t *gml_deref(float target, gm_instance_t *self, gm_instance_t *other);

/* User instance variables: vars[] holds reals, strs[] strings, vals[]
 * everything else. The NULL-tolerant forms are used for `target.var` where
 * the target may not resolve. */
static inline float gml_ivar(const gm_instance_t *p, int i)
{
    return p != NULL ? p->vars[i] : 0.0f;
}

static inline void gml_ivar_set(gm_instance_t *p, int i, float v)
{
    if (p != NULL) {
        p->vars[i] = v;
    }
}

static inline const char *gml_svar(const gm_instance_t *p, int i)
{
    return p != NULL ? gml_s(p->strs[i]) : "";
}

static inline void gml_svar_set(gm_instance_t *p, int i, const char *v)
{
    if (p != NULL) {
        p->strs[i] = gml_s(v);
    }
}

static inline gm_value_t gml_vvar(const gm_instance_t *p, int i)
{
    return p != NULL ? p->vals[i] : gm_value_undefined();
}

static inline void gml_vvar_set(gm_instance_t *p, int i, gm_value_t v)
{
    if (p != NULL) {
        p->vals[i] = v;
    }
}

/* Storage slot for array writes; a scratch slot for NULL instances. */
gm_value_t *gml_vvar_ref(gm_instance_t *p, int i);

/* ---- arrays ------------------------------------------------------------------------------- */

static inline gm_value_t gml_aget(gm_value_t a, float i)
{
    return gm_array_get(a, (int)gm_to_int32(i));
}

static inline gm_value_t *gml_aref(gm_value_t *slot, float i)
{
    return gm_array_ref(slot, (int)gm_to_int32(i));
}

static inline void gml_aset(gm_value_t *slot, float i, gm_value_t v)
{
    gm_array_set(slot, (int)gm_to_int32(i), v);
}

/* Array literal: [a, b, c] */
gm_value_t gml_array_lit(int n, const gm_value_t *items);

/* Struct accessor s[$ key]. Structs only come from json_parse, which is still
 * pending, so these are placeholders: reads yield undefined, writes are
 * dropped, and both are recorded with gml_pending_hit. */
gm_value_t gml_struct_get(gm_value_t s, gm_value_t key);
void gml_struct_set(gm_value_t s, gm_value_t key, gm_value_t v);

/* repeat (n): iteration count (yyGetInt32). */
static inline int32_t gml_repeat_count(float n)
{
    return gm_to_int32(n);
}

/* ---- lowered built-ins ---------------------------------------------------------------------- */

static inline float gml_is_real(gm_value_t v)
{
    return v.kind == GM_VALUE_REAL ? 1.0f : 0.0f;
}

static inline float gml_is_string(gm_value_t v)
{
    return v.kind == GM_VALUE_STRING ? 1.0f : 0.0f;
}

static inline float gml_is_array(gm_value_t v)
{
    return v.kind == GM_VALUE_ARRAY ? 1.0f : 0.0f;
}

static inline float gml_is_undefined(gm_value_t v)
{
    return v.kind == GM_VALUE_UNDEFINED ? 1.0f : 0.0f;
}

static inline float gml_array_length(gm_value_t v)
{
    return (float)gm_array_length(v);
}

/* real(): parseFloat for strings (Function_String.js L106). */
float gml_to_real(gm_value_t v);

/* ---- typed ds_map reads -----------------------------------------------------------------
 * The emitter reads a map with the representation its destination needs
 * (ds_map lookups are context-typed, see gml_type_check.py). Missing keys
 * and invalid maps read as undefined converted: 0 / "undefined". */
float gml_ds_map_find_real(float map, const char *key);
const char *gml_ds_map_find_str(float map, const char *key);
/* is_undefined(map[? key]) */
float gml_ds_map_missing(float map, const char *key);

/* bool() (Function_String.js L161). */
static inline float gml_to_bool(gm_value_t v)
{
    return gm_value_to_bool(v) ? 1.0f : 0.0f;
}

/* int64(): the port keeps reals, so this truncates toward zero. */
static inline float gml_int64(float d)
{
    return isfinite(d) ? truncf(d) : 0.0f;
}

/* ---- events and scripts --------------------------------------------------------------------- */

typedef void (*gml_event_fn)(gm_instance_t *self, gm_instance_t *other);
typedef gm_value_t (*gml_script_fn)(gm_instance_t *self, gm_instance_t *other, int argc,
                                    const gm_value_t *argv);

/* Event handler defined directly on an object. `type` / `number` use the
 * GameMaker event codes (.yy eventType / eventNum; collision events use the
 * other object's index as number). */
typedef struct gml_event_entry {
    int object_index;
    int type;
    int number;
    gml_event_fn fn;
} gml_event_entry_t;

/* Tables generated for a whole project (gml_game.c). */
typedef struct gml_game {
    int object_count;
    const int *object_parents;         /* parent object index, or -1 */
    int event_count;
    const gml_event_entry_t *events;   /* sorted by (object, type, number) */
    int script_count;
    const gml_script_fn *scripts;      /* boxed trampolines, by script index */
    void (*visit_roots)(gm_heap_visit_fn visit); /* global value roots */
    void (*global_init)(void);         /* gml_pragma("global", ...) scripts, or NULL */
} gml_game_t;

/* Installs the generated tables (borrowed). */
void gml_rt_install(const gml_game_t *game);
const gml_game_t *gml_rt_game(void);

/* Runs the installed game's gml_pragma("global") scripts (once, before the first
 * room; assets must already be installed). */
void gml_rt_global_init(void);

/* Generated event functions bracket their body with push/pop so that
 * event_inherited() knows which object's handler is running; push also
 * enters the (self, other) context (gm_ctx_push) and pop leaves it. */
void gml_event_push(gm_instance_t *self, gm_instance_t *other, int object_index, int type, int number);
void gml_event_pop(void);

/* event_inherited(): runs the nearest ancestor's handler for the current
 * event (no-op at the root or outside events). */
void gml_event_inherited(gm_instance_t *self, gm_instance_t *other);

/* Handler of event (type, number) for an object, inherited through the parent
 * chain (the generated event table), or NULL. */
gml_event_fn gml_find_event(int object_index, int type, int number);

/* Handler defined on the object itself (no inheritance), or NULL
 * (gm_loop_hooks_t.find_own_event). */
gml_event_fn gml_find_own_event(int object_index, int type, int number);

/* Runs that handler on inst with self == other == inst (gm_room_hooks_t.perform). */
void gml_perform_event(gm_instance_t *inst, int type, int number);

/* script_execute(ind, ...) with a non-constant script index. */
gm_value_t gml_script_execute(gm_instance_t *self, gm_instance_t *other, float script,
                              int argc, const gm_value_t *argv);

/* ---- pending built-ins ----------------------------------------------------------------------- */

/* Records that a placeholder built-in was reached (distinct names, in
 * first-use order), so parity work can see what is still missing. */
void gml_pending_hit(const char *name);
int gml_pending_count(void);
const char *gml_pending_name(int index);
void gml_pending_reset(void);

/* Copies a string into caller-owned storage (truncating) and returns it, for
 * built-in variables that are not collector roots. */
const char *gml_keep_str(const char *s, char *buf, size_t size);

/* ---- collection ------------------------------------------------------------------------------ */

/* Safe-point collection: roots are every live instance's strs[] / vals[] and
 * the installed game's globals. */
void gml_collect_garbage(void);
void gml_collect_garbage_force(void);
void gml_room_begin(int room);

/* Resets gml_rt state (event stack, with/context stacks, pending list,
 * installed game). */
void gml_rt_reset(void);

#endif /* GML_RT_H */
